apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: wttrin-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: wttrin-source
    properties:
      period: 10000
      wttrLocation: 'Tokyo'
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: log-action
      properties:
        multiline: true
        showAllProperties: true
        showHeaders: true
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
    properties:
      showStreams: true
