apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: s3-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-s3-source
    properties:
      bucketNameOrArn: test
      region: ap-east-1
      accessKey: test
      secretKey: test
      overrideEndpoint: true
      uriEndpointOverride: 'http://localhost:4566'
      autoCreateBucket: true
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: log-action
      properties:
        level: DEBUG
        showHeaders: true
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
    properties:
      level: DEBUG
      showHeaders: true
