apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: wttrin-jslt-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: wttrin-source
    properties:
      period: 10000
      wttrLocation: 'Tokyo'
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-action
    properties:
      multiline: true
      showAllProperties: true
      showHeaders: true
      showStreams: true
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: jslt-action
    properties:
      template: file:./bindings/wttrin-jslt-template.json
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
    properties:
      multiline: true
      showAllProperties: true
      showHeaders: true
